#pragma once

#define CLIENT_WIN_WIDTH 1280
#define CLIENT_WIN_HEIGHT 720
#define CLIENT_WIN_DEFAULT_FRAMERATE 60
#define CLIENT_WIN_STICKY 1
#define CLIENT_WIN_VSYNC 1
#define CLIENT_VIEW_DISTANCE 16
#define CLIENT_MINECRAFT_LIKE_CAMERA true

void client_start(void);
